[package]
name = "server_test"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]
edition = "2018"

[dependencies]
protocol = { path = "../protocol" }
websocket = "0.26.3"
serde_json = "1.0.79"
