[package]
name = "refunct-tas-ingame-lib"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]
edition = "2021"

[dependencies]
protocol = { path = "../protocol" }
once_cell = "1.9.0"
byteorder = "1.0.0"
backtrace = "0.3"
failure = "0.1"
rtil_derive = { path = "../rtil_derive" }
crossbeam-channel = "0.3.8"
memoffset = "0.5.5"
object = { version = "0.21.1", default-features = false, features = ["read"] }
rebo = { path = "../../rebo/rebo" }
itertools = "0.10.1"
clipboard = "0.5.0"
thiserror = "1.0.30"

[target.'cfg(unix)'.dependencies]
libc = "0.2.20"
dynsym = { path = "../dynsym" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.7", features = ["winnt", "tlhelp32", "handleapi", "processthreadsapi", "minwindef", "impl-default"] }
kernel32-sys = "0.2.2"

[lib]
name = "rtil"
crate_type = ["dylib"]

[profile.dev]
panic = 'abort'

[profile.release]
debug = true
debug-assertions = true
panic = 'abort'