[package]
name = "refunct-tas-ingame-lib"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]
edition = "2021"

[dependencies]
protocol = { path = "../protocol" }
once_cell = "1.9.0"
byteorder = "1.4.3"
backtrace = "0.3.64"
rtil_derive = { path = "../rtil_derive" }
crossbeam-channel = "0.5.2"
memoffset = "0.6.5"
#object = "0.28.3"
#rebo = { path = "../../rebo/rebo" }
rebo = { git = "https://github.com/oberien/rebo", rev = "017a85cef950e171f96b9c0bf75397e8f617914d" }
itertools = "0.10.3"
clipboard = "0.5.0"
thiserror = "1.0.30"
serde_json = "1.0.79"
websocket = "0.26.3"
dirs = "4.0.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.119"
dynsym = { path = "../dynsym" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winnt", "tlhelp32", "handleapi", "processthreadsapi", "minwindef", "impl-default", "memoryapi", "libloaderapi"] }

[lib]
name = "rtil"
crate_type = ["dylib"]

[profile.dev]
panic = 'abort'

[profile.release]
debug = true
debug-assertions = true
panic = 'abort'