[package]
name = "server"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]
edition = "2018"

[dependencies]
protocol = { path = "../protocol" }
tokio = "0.1.18"
futures = "0.1.26"
bytes = "0.4.12"
